// Mocks generated by Mockito 5.4.6 from annotations
// in budget_tracker/test/features/dashboard/presentation/bloc/dashboard_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:budget_tracker/features/budget/domain/entities/budget_error.dart'
    as _i7;
import 'package:budget_tracker/features/budget/domain/entities/budget_summary_entity.dart'
    as _i8;
import 'package:budget_tracker/features/budget/domain/repository/budget_repository.dart'
    as _i2;
import 'package:budget_tracker/features/budget/domain/services/budget_calculation_service.dart'
    as _i3;
import 'package:budget_tracker/features/budget/domain/usecases/get_budget_summary_usecase.dart'
    as _i5;
import 'package:budget_tracker/features/dashboard/domain/entities/recent_expense_entity.dart'
    as _i11;
import 'package:budget_tracker/features/dashboard/domain/repository/dashboard_repository.dart'
    as _i4;
import 'package:budget_tracker/features/dashboard/domain/usecases/get_recent_expenses_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBudgetRepository_0 extends _i1.SmartFake
    implements _i2.BudgetRepository {
  _FakeBudgetRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetCalculationService_1 extends _i1.SmartFake
    implements _i3.BudgetCalculationService {
  _FakeBudgetCalculationService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardRepository_2 extends _i1.SmartFake
    implements _i4.DashboardRepository {
  _FakeDashboardRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetBudgetSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBudgetSummaryUseCase extends _i1.Mock
    implements _i5.GetBudgetSummaryUseCase {
  MockGetBudgetSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BudgetRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBudgetRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BudgetRepository);

  @override
  _i3.BudgetCalculationService get calculationService =>
      (super.noSuchMethod(
            Invocation.getter(#calculationService),
            returnValue: _FakeBudgetCalculationService_1(
              this,
              Invocation.getter(#calculationService),
            ),
          )
          as _i3.BudgetCalculationService);

  @override
  _i6.Future<_i7.BudgetResult<_i8.BudgetSummaryEntity>> call({
    DateTime? referenceDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#referenceDate: referenceDate}),
            returnValue:
                _i6.Future<_i7.BudgetResult<_i8.BudgetSummaryEntity>>.value(
                  _i9.dummyValue<_i7.BudgetResult<_i8.BudgetSummaryEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #referenceDate: referenceDate,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i7.BudgetResult<_i8.BudgetSummaryEntity>>);
}

/// A class which mocks [GetRecentExpensesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecentExpensesUseCase extends _i1.Mock
    implements _i10.GetRecentExpensesUseCase {
  MockGetRecentExpensesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DashboardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeDashboardRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.DashboardRepository);

  @override
  _i6.Future<List<_i11.RecentExpenseEntity>> call({
    int? limit = 5,
    DateTime? referenceDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #limit: limit,
              #referenceDate: referenceDate,
            }),
            returnValue: _i6.Future<List<_i11.RecentExpenseEntity>>.value(
              <_i11.RecentExpenseEntity>[],
            ),
          )
          as _i6.Future<List<_i11.RecentExpenseEntity>>);
}
