// Mocks generated by Mockito 5.4.6 from annotations
// in monivo/test/features/settings/presentation/bloc/settings_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:monivo/features/settings/domain/entities/app_settings.dart'
    as _i11;
import 'package:monivo/features/settings/domain/entities/notification_settings.dart'
    as _i15;
import 'package:monivo/features/settings/domain/entities/settings_failure.dart'
    as _i10;
import 'package:monivo/features/settings/domain/repository/settings_repository.dart'
    as _i2;
import 'package:monivo/features/settings/domain/services/backup_service.dart'
    as _i6;
import 'package:monivo/features/settings/domain/services/biometric_service.dart'
    as _i3;
import 'package:monivo/features/settings/domain/services/export_service.dart'
    as _i4;
import 'package:monivo/features/settings/domain/services/import_service.dart'
    as _i5;
import 'package:monivo/features/settings/domain/services/notification_service.dart'
    as _i7;
import 'package:monivo/features/settings/domain/usecases/backup_data_usecase.dart'
    as _i19;
import 'package:monivo/features/settings/domain/usecases/export_data_usecase.dart'
    as _i17;
import 'package:monivo/features/settings/domain/usecases/import_data_usecase.dart'
    as _i18;
import 'package:monivo/features/settings/domain/usecases/load_settings_usecase.dart'
    as _i8;
import 'package:monivo/features/settings/domain/usecases/reset_budget_usecase.dart'
    as _i21;
import 'package:monivo/features/settings/domain/usecases/restore_data_usecase.dart'
    as _i20;
import 'package:monivo/features/settings/domain/usecases/schedule_notifications_usecase.dart'
    as _i22;
import 'package:monivo/features/settings/domain/usecases/update_biometric_usecase.dart'
    as _i16;
import 'package:monivo/features/settings/domain/usecases/update_currency_usecase.dart'
    as _i13;
import 'package:monivo/features/settings/domain/usecases/update_notification_settings_usecase.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingsRepository_0 extends _i1.SmartFake
    implements _i2.SettingsRepository {
  _FakeSettingsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBiometricAvailability_1 extends _i1.SmartFake
    implements _i3.BiometricAvailability {
  _FakeBiometricAvailability_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExportService_2 extends _i1.SmartFake implements _i4.ExportService {
  _FakeExportService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImportService_3 extends _i1.SmartFake implements _i5.ImportService {
  _FakeImportService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackupService_4 extends _i1.SmartFake implements _i6.BackupService {
  _FakeBackupService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationService_5 extends _i1.SmartFake
    implements _i7.NotificationService {
  _FakeNotificationService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoadSettingsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadSettingsUseCase extends _i1.Mock
    implements _i8.LoadSettingsUseCase {
  MockLoadSettingsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SettingsRepository);

  @override
  _i9.Future<_i10.SettingsResult<_i11.AppSettings>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i9.Future<_i10.SettingsResult<_i11.AppSettings>>.value(
                  _i12.dummyValue<_i10.SettingsResult<_i11.AppSettings>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i9.Future<_i10.SettingsResult<_i11.AppSettings>>);
}

/// A class which mocks [UpdateCurrencyUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCurrencyUseCase extends _i1.Mock
    implements _i13.UpdateCurrencyUseCase {
  MockUpdateCurrencyUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SettingsRepository);

  @override
  _i9.Future<_i10.SettingsResult<void>> call(String? code, String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#call, [code, symbol]),
            returnValue: _i9.Future<_i10.SettingsResult<void>>.value(
              _i12.dummyValue<_i10.SettingsResult<void>>(
                this,
                Invocation.method(#call, [code, symbol]),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<void>>);
}

/// A class which mocks [UpdateNotificationSettingsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNotificationSettingsUseCase extends _i1.Mock
    implements _i14.UpdateNotificationSettingsUseCase {
  MockUpdateNotificationSettingsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SettingsRepository);

  @override
  _i9.Future<_i10.SettingsResult<void>> call(
    _i15.NotificationSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [settings]),
            returnValue: _i9.Future<_i10.SettingsResult<void>>.value(
              _i12.dummyValue<_i10.SettingsResult<void>>(
                this,
                Invocation.method(#call, [settings]),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<void>>);
}

/// A class which mocks [UpdateBiometricUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateBiometricUseCase extends _i1.Mock
    implements _i16.UpdateBiometricUseCase {
  MockUpdateBiometricUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSettingsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SettingsRepository);

  @override
  _i9.Future<_i10.SettingsResult<void>> call(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#call, [enabled]),
            returnValue: _i9.Future<_i10.SettingsResult<void>>.value(
              _i12.dummyValue<_i10.SettingsResult<void>>(
                this,
                Invocation.method(#call, [enabled]),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<void>>);
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i3.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.BiometricAvailability> getAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailability, []),
            returnValue: _i9.Future<_i3.BiometricAvailability>.value(
              _FakeBiometricAvailability_1(
                this,
                Invocation.method(#getAvailability, []),
              ),
            ),
          )
          as _i9.Future<_i3.BiometricAvailability>);

  @override
  _i9.Future<bool> canUseBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#canUseBiometrics, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> authenticate({
    String? reason = 'Unlock Monivo',
    bool? useErrorDialogs = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #reason: reason,
              #useErrorDialogs: useErrorDialogs,
            }),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}

/// A class which mocks [ExportDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportDataUseCase extends _i1.Mock implements _i17.ExportDataUseCase {
  MockExportDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ExportService get exportService =>
      (super.noSuchMethod(
            Invocation.getter(#exportService),
            returnValue: _FakeExportService_2(
              this,
              Invocation.getter(#exportService),
            ),
          )
          as _i4.ExportService);

  @override
  _i9.Future<_i10.SettingsResult<String>> call({bool? csv = true}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#csv: csv}),
            returnValue: _i9.Future<_i10.SettingsResult<String>>.value(
              _i12.dummyValue<_i10.SettingsResult<String>>(
                this,
                Invocation.method(#call, [], {#csv: csv}),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<String>>);
}

/// A class which mocks [ImportDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportDataUseCase extends _i1.Mock implements _i18.ImportDataUseCase {
  MockImportDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ImportService get importService =>
      (super.noSuchMethod(
            Invocation.getter(#importService),
            returnValue: _FakeImportService_3(
              this,
              Invocation.getter(#importService),
            ),
          )
          as _i5.ImportService);

  @override
  _i9.Future<_i10.SettingsResult<int>> call(
    String? path, {
    required bool? json,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [path], {#json: json}),
            returnValue: _i9.Future<_i10.SettingsResult<int>>.value(
              _i12.dummyValue<_i10.SettingsResult<int>>(
                this,
                Invocation.method(#call, [path], {#json: json}),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<int>>);
}

/// A class which mocks [BackupDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupDataUseCase extends _i1.Mock implements _i19.BackupDataUseCase {
  MockBackupDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BackupService get backupService =>
      (super.noSuchMethod(
            Invocation.getter(#backupService),
            returnValue: _FakeBackupService_4(
              this,
              Invocation.getter(#backupService),
            ),
          )
          as _i6.BackupService);

  @override
  _i9.Future<_i10.SettingsResult<String>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i9.Future<_i10.SettingsResult<String>>.value(
              _i12.dummyValue<_i10.SettingsResult<String>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<String>>);
}

/// A class which mocks [RestoreDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestoreDataUseCase extends _i1.Mock
    implements _i20.RestoreDataUseCase {
  MockRestoreDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BackupService get backupService =>
      (super.noSuchMethod(
            Invocation.getter(#backupService),
            returnValue: _FakeBackupService_4(
              this,
              Invocation.getter(#backupService),
            ),
          )
          as _i6.BackupService);

  @override
  _i9.Future<_i10.SettingsResult<String>> call(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#call, [path]),
            returnValue: _i9.Future<_i10.SettingsResult<String>>.value(
              _i12.dummyValue<_i10.SettingsResult<String>>(
                this,
                Invocation.method(#call, [path]),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<String>>);
}

/// A class which mocks [ResetBudgetUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetBudgetUseCase extends _i1.Mock
    implements _i21.ResetBudgetUseCase {
  MockResetBudgetUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.SettingsResult<String>> resetBudgetAmount(
    double? newAmount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetBudgetAmount, [newAmount]),
            returnValue: _i9.Future<_i10.SettingsResult<String>>.value(
              _i12.dummyValue<_i10.SettingsResult<String>>(
                this,
                Invocation.method(#resetBudgetAmount, [newAmount]),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<String>>);

  @override
  _i9.Future<_i10.SettingsResult<String>> resetCurrentMonth() =>
      (super.noSuchMethod(
            Invocation.method(#resetCurrentMonth, []),
            returnValue: _i9.Future<_i10.SettingsResult<String>>.value(
              _i12.dummyValue<_i10.SettingsResult<String>>(
                this,
                Invocation.method(#resetCurrentMonth, []),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<String>>);
}

/// A class which mocks [ScheduleNotificationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleNotificationsUseCase extends _i1.Mock
    implements _i22.ScheduleNotificationsUseCase {
  MockScheduleNotificationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.NotificationService get notificationService =>
      (super.noSuchMethod(
            Invocation.getter(#notificationService),
            returnValue: _FakeNotificationService_5(
              this,
              Invocation.getter(#notificationService),
            ),
          )
          as _i7.NotificationService);

  @override
  _i9.Future<_i10.SettingsResult<void>> call(_i11.AppSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#call, [settings]),
            returnValue: _i9.Future<_i10.SettingsResult<void>>.value(
              _i12.dummyValue<_i10.SettingsResult<void>>(
                this,
                Invocation.method(#call, [settings]),
              ),
            ),
          )
          as _i9.Future<_i10.SettingsResult<void>>);
}
