// Mocks generated by Mockito 5.4.6 from annotations
// in budget_tracker/test/features/budget/domain/usecases/get_budget_list_summary_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:budget_tracker/core/domain/entities/budget_entity.dart' as _i2;
import 'package:budget_tracker/features/budget/domain/entities/budget_error.dart'
    as _i7;
import 'package:budget_tracker/features/budget/domain/entities/budget_filter.dart'
    as _i6;
import 'package:budget_tracker/features/budget/domain/entities/monthly_statistics_entity.dart'
    as _i3;
import 'package:budget_tracker/features/budget/domain/repository/budget_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBudgetEntity_0 extends _i1.SmartFake implements _i2.BudgetEntity {
  _FakeBudgetEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMonthlyStatisticsEntity_1 extends _i1.SmartFake
    implements _i3.MonthlyStatisticsEntity {
  _FakeMonthlyStatisticsEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i4.BudgetRepository {
  MockBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BudgetEntity?> getActiveBudget() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveBudget, []),
            returnValue: _i5.Future<_i2.BudgetEntity?>.value(),
          )
          as _i5.Future<_i2.BudgetEntity?>);

  @override
  _i5.Future<String?> getActiveBudgetId() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveBudgetId, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setActiveBudgetId(String? budgetId) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveBudgetId, [budgetId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.BudgetEntity?> getBudgetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetById, [id]),
            returnValue: _i5.Future<_i2.BudgetEntity?>.value(),
          )
          as _i5.Future<_i2.BudgetEntity?>);

  @override
  _i5.Future<List<_i2.BudgetEntity>> getAllBudgets({
    _i6.BudgetQueryOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBudgets, [], {#options: options}),
            returnValue: _i5.Future<List<_i2.BudgetEntity>>.value(
              <_i2.BudgetEntity>[],
            ),
          )
          as _i5.Future<List<_i2.BudgetEntity>>);

  @override
  _i5.Future<_i2.BudgetEntity> createBudget(_i2.BudgetEntity? budget) =>
      (super.noSuchMethod(
            Invocation.method(#createBudget, [budget]),
            returnValue: _i5.Future<_i2.BudgetEntity>.value(
              _FakeBudgetEntity_0(
                this,
                Invocation.method(#createBudget, [budget]),
              ),
            ),
          )
          as _i5.Future<_i2.BudgetEntity>);

  @override
  _i5.Future<_i2.BudgetEntity> updateBudget(_i2.BudgetEntity? budget) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudget, [budget]),
            returnValue: _i5.Future<_i2.BudgetEntity>.value(
              _FakeBudgetEntity_0(
                this,
                Invocation.method(#updateBudget, [budget]),
              ),
            ),
          )
          as _i5.Future<_i2.BudgetEntity>);

  @override
  _i5.Future<void> deleteBudget(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudget, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.BudgetEntity> setBudgetArchived(
    String? id, {
    required bool? archived,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setBudgetArchived, [id], {#archived: archived}),
            returnValue: _i5.Future<_i2.BudgetEntity>.value(
              _FakeBudgetEntity_0(
                this,
                Invocation.method(
                  #setBudgetArchived,
                  [id],
                  {#archived: archived},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.BudgetEntity>);

  @override
  _i5.Future<_i2.BudgetEntity> duplicateBudget(
    String? id, {
    required String? newName,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #duplicateBudget,
              [id],
              {#newName: newName, #startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i5.Future<_i2.BudgetEntity>.value(
              _FakeBudgetEntity_0(
                this,
                Invocation.method(
                  #duplicateBudget,
                  [id],
                  {#newName: newName, #startDate: startDate, #endDate: endDate},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.BudgetEntity>);

  @override
  _i5.Future<_i3.MonthlyStatisticsEntity> getBudgetStatistics(
    String? budgetId, {
    DateTime? referenceDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBudgetStatistics,
              [budgetId],
              {#referenceDate: referenceDate},
            ),
            returnValue: _i5.Future<_i3.MonthlyStatisticsEntity>.value(
              _FakeMonthlyStatisticsEntity_1(
                this,
                Invocation.method(
                  #getBudgetStatistics,
                  [budgetId],
                  {#referenceDate: referenceDate},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.MonthlyStatisticsEntity>);

  @override
  _i5.Future<double> getTodaySpending(
    String? budgetId, {
    DateTime? referenceDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTodaySpending,
              [budgetId],
              {#referenceDate: referenceDate},
            ),
            returnValue: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<int> getRemainingDays(
    String? budgetId, {
    DateTime? referenceDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRemainingDays,
              [budgetId],
              {#referenceDate: referenceDate},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i7.BudgetResult<_i4.BudgetCalculationContext>>
  getCalculationContext(String? budgetId, {DateTime? referenceDate}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCalculationContext,
              [budgetId],
              {#referenceDate: referenceDate},
            ),
            returnValue:
                _i5.Future<
                  _i7.BudgetResult<_i4.BudgetCalculationContext>
                >.value(
                  _i8.dummyValue<
                    _i7.BudgetResult<_i4.BudgetCalculationContext>
                  >(
                    this,
                    Invocation.method(
                      #getCalculationContext,
                      [budgetId],
                      {#referenceDate: referenceDate},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i7.BudgetResult<_i4.BudgetCalculationContext>>);

  @override
  _i5.Future<void> updateBudgetRemainingAmount(String? budgetId) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudgetRemainingAmount, [budgetId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
