import 'package:flutter/material.dart';

import '../../features/settings/domain/entities/color_palette_entity.dart';

/// Defines a complete light + dark color scheme pair for a palette.
///
/// Each palette provides a fully fleshed-out [ColorScheme] for both brightness
/// values, plus semantic colors for financial app concepts (income, expense,
/// etc.).
class PaletteColors {
  final ColorScheme lightScheme;
  final ColorScheme darkScheme;

  // Semantic colors — light
  final Color incomeLight;
  final Color expenseLight;
  final Color successLight;
  final Color warningLight;
  final Color infoLight;
  final Color primaryGradientStartLight;
  final Color primaryGradientEndLight;

  // Semantic colors — dark
  final Color incomeDark;
  final Color expenseDark;
  final Color successDark;
  final Color warningDark;
  final Color infoDark;
  final Color primaryGradientStartDark;
  final Color primaryGradientEndDark;

  const PaletteColors({
    required this.lightScheme,
    required this.darkScheme,
    required this.incomeLight,
    required this.expenseLight,
    required this.successLight,
    required this.warningLight,
    required this.infoLight,
    required this.primaryGradientStartLight,
    required this.primaryGradientEndLight,
    required this.incomeDark,
    required this.expenseDark,
    required this.successDark,
    required this.warningDark,
    required this.infoDark,
    required this.primaryGradientStartDark,
    required this.primaryGradientEndDark,
  });

  /// Returns the semantic color for a given brightness.
  Color income(Brightness b) =>
      b == Brightness.light ? incomeLight : incomeDark;
  Color expense(Brightness b) =>
      b == Brightness.light ? expenseLight : expenseDark;
  Color success(Brightness b) =>
      b == Brightness.light ? successLight : successDark;
  Color warning(Brightness b) =>
      b == Brightness.light ? warningLight : warningDark;
  Color info(Brightness b) => b == Brightness.light ? infoLight : infoDark;
  Color primaryGradientStart(Brightness b) => b == Brightness.light
      ? primaryGradientStartLight
      : primaryGradientStartDark;
  Color primaryGradientEnd(Brightness b) =>
      b == Brightness.light ? primaryGradientEndLight : primaryGradientEndDark;
}

/// Retrieves the full [PaletteColors] for a given [ColorPalette].
PaletteColors getPaletteColors(ColorPalette palette) {
  switch (palette) {
    case ColorPalette.defaultPalette:
      return _defaultPalette;
    case ColorPalette.blossomVapor:
      return _blossomVapor;
    case ColorPalette.mahoganyBlaze:
      return _mahoganyBlaze;
    case ColorPalette.ocean:
      return _oceanPalette;
    case ColorPalette.forest:
      return _forestPalette;
    case ColorPalette.sunset:
      return _sunsetPalette;
    case ColorPalette.violet:
      return _violetPalette;
    case ColorPalette.rose:
      return _rosePalette;
  }
}

// =============================================================================
// Shared "error" tonal roles.
//
// Error is a *system* signal (form validation, failed requests) rather than
// a brand color, so — matching how 6 of the 8 original palettes already did
// it — every palette uses the exact same error family. A user should be able
// to recognize "something went wrong" instantly regardless of which palette
// they've chosen, the same way `expense`/`income` should read the same way
// once you know the app. Defining them once here also means the ColorScheme
// constructors below aren't repeating the same 4 hex values 8 times.
// =============================================================================
const Color _errorLight = Color(0xFFD65C62);
const Color _onErrorLight = Color(0xFF3D0F12);
const Color _errorContainerLight = Color(0xFFEED3D4);
const Color _onErrorContainerLight = Color(0xFF451114);

const Color _errorDark = Color(0xFFE4777C);
const Color _onErrorDark = Color(0xFF440E10);
const Color _errorContainerDark = Color(0xFF6E2B2E);
const Color _onErrorContainerDark = Color(0xFFECDFDF);

// =============================================================================
// Default Palette  (indigo / teal / violet)
// =============================================================================
//
// Tertiary was previously left unspecified (auto-generated by fromSeed).
// Adding an explicit violet tertiary gives this palette a real triadic
// spread — indigo (primary), teal (secondary), violet (tertiary) — so chips,
// tags, and secondary CTAs have a genuinely distinct third color to draw
// from instead of whatever the seed algorithm happened to derive.

final PaletteColors _defaultPalette = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF3155D4),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD1D8EF),
    onPrimaryContainer: Color(0xFF0F1C48),
    secondary: Color(0xFF159A9C),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFCFF1F2),
    onSecondaryContainer: Color(0xFF0A4B4C),
    tertiary: Color(0xFF7B4DCB),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDDD4ED),
    onTertiaryContainer: Color(0xFF251443),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF182033),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF4C6FE3),
    onPrimary: Color(0xFF0B1947),
    primaryContainer: Color(0xFF283971),
    onPrimaryContainer: Color(0xFFDEE2ED),
    secondary: Color(0xFF31B6B5),
    onSecondary: Color(0xFF114040),
    secondaryContainer: Color(0xFF306969),
    onSecondaryContainer: Color(0xFFE0EBEB),
    tertiary: Color(0xFFB79FDF),
    onTertiary: Color(0xFF24143D),
    tertiaryContainer: Color(0xFF463267),
    onTertiaryContainer: Color(0xFFE4E0EB),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF11172A),
    onSurface: Color(0xFFF4F7FF),
  ),
  incomeLight: const Color(0xFF298E5C),
  expenseLight: const Color(0xFFBC442F),
  successLight: const Color(0xFF2C9666),
  warningLight: const Color(0xFFD48A35),
  infoLight: const Color(0xFF3786BE),
  primaryGradientStartLight: const Color(0xFF1C3AA2),
  primaryGradientEndLight: const Color(0xFF5B78DD),
  incomeDark: const Color(0xFF53C68C),
  expenseDark: const Color(0xFFD78375),
  successDark: const Color(0xFF5EC999),
  warningDark: const Color(0xFFDEB17C),
  infoDark: const Color(0xFF79ADD2),
  primaryGradientStartDark: const Color(0xFF1A43CE),
  primaryGradientEndDark: const Color(0xFF7892EA),
);

// =============================================================================
// Ocean Palette  (blue / cyan / coral)
// =============================================================================
//
// The original tertiary (0xFF48CAE4) sat in the same cyan family as the
// secondary (0xFF00B4D8) — next to each other they read as "two shades of
// the same blue" instead of two distinct roles. Swapping tertiary for coral
// gives a genuine warm/cool split-complement (and doubles as an on-theme
// "coral reef" accent), so a tab indicator or badge in tertiary actually
// pops against the primary/secondary blues instead of blending in.

final PaletteColors _oceanPalette = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF0077B6),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFC9E7F7),
    onPrimaryContainer: Color(0xFF073750),
    secondary: Color(0xFF00B4D8),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFC9F0F7),
    onSecondaryContainer: Color(0xFF074450),
    tertiary: Color(0xFFF17B50),
    onTertiary: Color(0xFF471706),
    tertiaryContainer: Color(0xFFF4D7CD),
    onTertiaryContainer: Color(0xFF501A07),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF0A2540),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF48CAE4),
    onPrimary: Color(0xFF0A3D47),
    primaryContainer: Color(0xFF286571),
    onPrimaryContainer: Color(0xFFDEEBED),
    secondary: Color(0xFF00B4D8),
    onSecondary: Color(0xFF06404B),
    secondaryContainer: Color(0xFF1B6E7E),
    onSecondaryContainer: Color(0xFFDBECF0),
    tertiary: Color(0xFFF2A78C),
    onTertiary: Color(0xFF491908),
    tertiaryContainer: Color(0xFF743A25),
    onTertiaryContainer: Color(0xFFEEE2DD),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF0A1628),
    onSurface: Color(0xFFE8F4F8),
  ),
  incomeLight: const Color(0xFF298E75),
  expenseLight: const Color(0xFFBC2F3B),
  successLight: const Color(0xFF2C9673),
  warningLight: const Color(0xFFD4A435),
  infoLight: const Color(0xFF3791BE),
  primaryGradientStartLight: const Color(0xFF00486F),
  primaryGradientEndLight: const Color(0xFF0098E9),
  incomeDark: const Color(0xFF53C6A9),
  expenseDark: const Color(0xFFD7757D),
  successDark: const Color(0xFF5EC9A6),
  warningDark: const Color(0xFFDEC17C),
  infoDark: const Color(0xFF79B5D2),
  primaryGradientStartDark: const Color(0xFF18AFCD),
  primaryGradientEndDark: const Color(0xFF74D7EB),
);

// =============================================================================
// Forest Palette  (green / sage / clay)
// =============================================================================
//
// Real bug fixed here: the original `incomeLight` (0xFF2D6A4F) was byte-for-
// byte identical to `primary`. Any card showing an income amount next to a
// primary-colored button or app bar would have made the two indistinguishable.
// Income now sits at a more teal-shifted green, clearly apart from both
// primary and secondary. Tertiary also moves from a green-on-green
// (0xFF74C69D, too close to secondary) to a clay/rust tone for actual
// contrast.

final PaletteColors _forestPalette = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF2D6A4F),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD6EBE2),
    onPrimaryContainer: Color(0xFF1A3D2D),
    secondary: Color(0xFF52B788),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD6EBE1),
    onSecondaryContainer: Color(0xFF193D2D),
    tertiary: Color(0xFFB97646),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFEBDFD6),
    onTertiaryContainer: Color(0xFF3F2818),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF1B2E1B),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF52B788),
    onPrimary: Color(0xFF183A2A),
    primaryContainer: Color(0xFF32674E),
    onPrimaryContainer: Color(0xFFE0EBE6),
    secondary: Color(0xFF74C69D),
    onSecondary: Color(0xFF183A29),
    secondaryContainer: Color(0xFF32674D),
    onSecondaryContainer: Color(0xFFE0EBE6),
    tertiary: Color(0xFFCEA88D),
    onTertiary: Color(0xFF392619),
    tertiaryContainer: Color(0xFF674832),
    onTertiaryContainer: Color(0xFFEBE5E0),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF0C1A0F),
    onSurface: Color(0xFFE8F5E9),
  ),
  incomeLight: const Color(0xFF298E81), // was identical to primary — fixed
  expenseLight: const Color(0xFFBC422F),
  successLight: const Color(0xFF2C964F),
  warningLight: const Color(0xFFD49A35),
  infoLight: const Color(0xFF3786BE),
  primaryGradientStartLight: const Color(0xFF163A2A),
  primaryGradientEndLight: const Color(0xFF3C8E6A),
  incomeDark: const Color(0xFF53C6B6),
  expenseDark: const Color(0xFFD78275),
  successDark: const Color(0xFF5EC982),
  warningDark: const Color(0xFFDEBA7C),
  infoDark: const Color(0xFF79ADD2),
  primaryGradientStartDark: const Color(0xFF348E64),
  primaryGradientEndDark: const Color(0xFF76C6A1),
);

// =============================================================================
// Sunset Palette  (orange / red / yellow)
// =============================================================================
//
// Primary/secondary/tertiary were already a solid analogous warm run
// (orange → red → yellow) — left that intact. The fix here is `warning`:
// it used to sit almost on top of tertiary's yellow. Warning is now pulled
// down into a deeper, more saturated burnt-amber so it reads as "caution"
// rather than "decorative accent chip."

final PaletteColors _sunsetPalette = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFE85D04),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFF7DCCA),
    onPrimaryContainer: Color(0xFF502307),
    secondary: Color(0xFFDC2F02),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFF7D3CA),
    onSecondaryContainer: Color(0xFF501607),
    tertiary: Color(0xFFF9C31F),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFF6EBCB),
    onTertiaryContainer: Color(0xFF503E07),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFBF5),
    onSurface: Color(0xFF3D1C02),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFCBF49),
    onPrimary: Color(0xFF4B3406),
    primaryContainer: Color(0xFF7D5C1C),
    onPrimaryContainer: Color(0xFFEFE9DC),
    secondary: Color(0xFFF48C06),
    onSecondary: Color(0xFF4B2D06),
    secondaryContainer: Color(0xFF7C521D),
    onSecondaryContainer: Color(0xFFEFE7DC),
    tertiary: Color(0xFFF8D877),
    onTertiary: Color(0xFF4B3A06),
    tertiaryContainer: Color(0xFF796320),
    onTertiaryContainer: Color(0xFFEFEADC),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF1A0F05),
    onSurface: Color(0xFFFFF3E0),
  ),
  incomeLight: const Color(0xFF298E5F),
  expenseLight: const Color(0xFFBC2F46),
  successLight: const Color(0xFF2C966A),
  warningLight: const Color(0xFFD48535), // pulled apart from tertiary's yellow
  infoLight: const Color(0xFF3786BE),
  primaryGradientStartLight: const Color(0xFFA54000),
  primaryGradientEndLight: const Color(0xFFFB7824),
  incomeDark: const Color(0xFF53C690),
  expenseDark: const Color(0xFFD77585),
  successDark: const Color(0xFF5EC99D),
  warningDark: const Color(0xFFDEAD7C),
  infoDark: const Color(0xFF79ADD2),
  primaryGradientStartDark: const Color(0xFFFEA700),
  primaryGradientEndDark: const Color(0xFFFDD17B),
);

// =============================================================================
// Violet Palette  (violet / lavender / gold)
// =============================================================================
//
// Two real bugs fixed here: `infoLight` (0xFF7B2CBF) was identical to
// `primary`, and the original tertiary (0xFF9D4EDD) was just another purple
// next to primary/secondary — three purples in a row give you nothing to
// visually separate a tertiary chip from a primary button. Tertiary is now
// gold — violet + gold is a deliberate "royal" pairing that's also a true
// complement, so it actually stands apart. Info gets its own distinct blue.

final PaletteColors _violetPalette = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF7B2CBF),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFE1D2EF),
    onPrimaryContainer: Color(0xFF2D1046),
    secondary: Color(0xFFC77DFF),
    onSecondary: Color(0xFF2B0449),
    secondaryContainer: Color(0xFFE4C9F7),
    onSecondaryContainer: Color(0xFF300750),
    tertiary: Color(0xFFDDA940),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFF0E6D0),
    onTertiaryContainer: Color(0xFF4A360D),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF1A0A2E),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFC77DFF),
    onPrimary: Color(0xFF2E064B),
    primaryContainer: Color(0xFF531B7E),
    onPrimaryContainer: Color(0xFFE7DBF0),
    secondary: Color(0xFF9D4EDD),
    onSecondary: Color(0xFF2C0D44),
    secondaryContainer: Color(0xFF502B6E),
    onSecondaryContainer: Color(0xFFE6DFEC),
    tertiary: Color(0xFFE9CD96),
    onTertiary: Color(0xFF43310E),
    tertiaryContainer: Color(0xFF6D572C),
    onTertiaryContainer: Color(0xFFECE8DF),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF100820),
    onSurface: Color(0xFFF3E8FF),
  ),
  incomeLight: const Color(0xFF298E5F),
  expenseLight: const Color(0xFFBC2F75),
  successLight: const Color(0xFF2C9658),
  warningLight: const Color(0xFFD48535),
  infoLight: const Color(0xFF376FBE), // was identical to primary — fixed
  primaryGradientStartLight: const Color(0xFF561B89),
  primaryGradientEndLight: const Color(0xFF9449D5),
  incomeDark: const Color(0xFF53C690),
  expenseDark: const Color(0xFFD775A6),
  successDark: const Color(0xFF5EC98B),
  warningDark: const Color(0xFFDEAD7C),
  infoDark: const Color(0xFF799ED2),
  primaryGradientStartDark: const Color(0xFFA836FF),
  primaryGradientEndDark: const Color(0xFFDDB0FF),
);

// =============================================================================
// Rose Palette  (rose / pink / teal)
// =============================================================================
//
// Real bug fixed here: `expenseLight` (0xFFC9184A) was identical to primary
// — the exact same collision as forest's income issue, just on the other
// semantic color. Expense moves to a deeper, more orange-leaning red so it's
// unmistakably not "just the primary color." Tertiary swaps from
// pink-on-pink (0xFFFF758F, too close to secondary) to teal — a classic
// "rose gold + teal" contrast pairing that also happens to double nicely as
// this palette's money-green family.

final PaletteColors _rosePalette = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFC9184A),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFF2CED9),
    onPrimaryContainer: Color(0xFF4D091D),
    secondary: Color(0xFFFF4D6D),
    onSecondary: Color(0xFF490410),
    secondaryContainer: Color(0xFFF7C9D2),
    onSecondaryContainer: Color(0xFF500714),
    tertiary: Color(0xFF36A18F),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFD5ECE8),
    onTertiaryContainer: Color(0xFF16413A),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFBFC),
    onSurface: Color(0xFF2B0A10),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFF758F),
    onPrimary: Color(0xFF4B0613),
    primaryContainer: Color(0xFF7E1B2E),
    onPrimaryContainer: Color(0xFFF0DBDF),
    secondary: Color(0xFFFF4D6D),
    onSecondary: Color(0xFF4B0613),
    secondaryContainer: Color(0xFF7E1B2D),
    onSecondaryContainer: Color(0xFFF0DBDF),
    tertiary: Color(0xFF7ECEC1),
    onTertiary: Color(0xFF163B35),
    tertiaryContainer: Color(0xFF32675F),
    onTertiaryContainer: Color(0xFFE0EBE9),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF180A10),
    onSurface: Color(0xFFFFF0F3),
  ),
  incomeLight: const Color(0xFF298E5C),
  expenseLight: const Color(0xFFBC3B2F), // was identical to primary — fixed
  successLight: const Color(0xFF2C9658),
  warningLight: const Color(0xFFD49235),
  infoLight: const Color(0xFF377ABE),
  primaryGradientStartLight: const Color(0xFF8D0D31),
  primaryGradientEndLight: const Color(0xFFE62E62),
  incomeDark: const Color(0xFF53C68C),
  expenseDark: const Color(0xFFD77D75),
  successDark: const Color(0xFF5EC98B),
  warningDark: const Color(0xFFDEB67C),
  infoDark: const Color(0xFF79A6D2),
  primaryGradientStartDark: const Color(0xFFFF2E55),
  primaryGradientEndDark: const Color(0xFFFFA8B8),
);

// =============================================================================
// Blossom Vapor Palette  (pink / lavender / mint)
// =============================================================================
//
// Kept your original primary/secondary tonal roles as-is — they were already
// well-built. Two things changed: tertiary moves from a pink tint
// (0xFFFFB4C6, too close to primary) to mint, which turns this into the
// actual pink+lavender+mint "vaporwave" trio instead of pink+lavender+more
// pink. And `expenseLight`/`infoLight` (plus their dark counterparts) were
// exact duplicates of `primary` and `secondary` respectively — fixed so
// expense and info are each their own visually distinct color.

final PaletteColors _blossomVapor = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFE75A8C),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFD9E5),
    onPrimaryContainer: Color(0xFF5C0F32),
    secondary: Color(0xFF9B7EDE),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE8DFFF),
    onSecondaryContainer: Color(0xFF352465),
    tertiary: Color(0xFF66CCC4),
    onTertiary: Color(0xFF133936),
    tertiaryContainer: Color(0xFFD5ECEA),
    onTertiaryContainer: Color(0xFF16413E),
    error: _errorLight,
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFF8FB),
    onSurface: Color(0xFF32122A),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFF8FAE),
    onPrimary: Color(0xFF5C0F32),
    primaryContainer: Color(0xFF7A2A4C),
    onPrimaryContainer: Color(0xFFFFD9E5),
    secondary: Color(0xFFC3AFFF),
    onSecondary: Color(0xFF352465),
    secondaryContainer: Color(0xFF4E3B85),
    onSecondaryContainer: Color(0xFFE8DFFF),
    tertiary: Color(0xFFA3DCD7),
    onTertiary: Color(0xFF163B38),
    tertiaryContainer: Color(0xFF326763),
    onTertiaryContainer: Color(0xFFE0EBEA),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF1D0F1C),
    onSurface: Color(0xFFFBEFFA),
  ),
  incomeLight: const Color(0xFF298E5C),
  expenseLight: const Color(0xFFBC3B2F), // was identical to primary — fixed
  successLight: const Color(0xFF2C965D),
  warningLight: const Color(0xFFD49235),
  infoLight: const Color(0xFF375FBE), // was identical to secondary — fixed
  primaryGradientStartLight: const Color(0xFFC94270),
  primaryGradientEndLight: const Color(0xFFE75A8C),
  incomeDark: const Color(0xFF53C68C),
  expenseDark: const Color(0xFFD77D75),
  successDark: const Color(0xFF5EC990),
  warningDark: const Color(0xFFDEB67C),
  infoDark: const Color(0xFF7994D2),
  primaryGradientStartDark: const Color(0xFFE96C93),
  primaryGradientEndDark: const Color(0xFFFF8FAE),
);

// =============================================================================
// Mahogany Blaze Palette  (burnt orange / blue / gold)
// =============================================================================
//
// The tonal roles here were already well-built and already a genuine
// triadic spread (orange/blue/gold), so they're untouched. What needed
// fixing: `error` used a one-off red (0xFFD1453B) instead of the shared
// system error color every other palette uses — unified for consistency.
// And, same bug as rose/blossomVapor: `expenseLight`/`expenseDark` were
// identical to `primary`, and `infoLight`/`infoDark` were identical to
// `secondary`. Both fixed.

final PaletteColors _mahoganyBlaze = PaletteColors(
  lightScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFF94C00),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFDACB),
    onPrimaryContainer: Color(0xFF4A1600),
    secondary: Color(0xFF4B7FA0),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD3E8F2),
    onSecondaryContainer: Color(0xFF11324A),
    tertiary: Color(0xFFE0A526),
    onTertiary: Color(0xFF3D2A00),
    tertiaryContainer: Color(0xFFFAE7BD),
    onTertiaryContainer: Color(0xFF4A3A18),
    error: _errorLight, // was a one-off red — unified with the system error
    onError: _onErrorLight,
    errorContainer: _errorContainerLight,
    onErrorContainer: _onErrorContainerLight,
    surface: Color(0xFFFFFBF8),
    onSurface: Color(0xFF2B160E),
  ),
  darkScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFF8659),
    onPrimary: Color(0xFF4A1600),
    primaryContainer: Color(0xFF7A2D0A),
    onPrimaryContainer: Color(0xFFFFDACB),
    secondary: Color(0xFF7BA5C2),
    onSecondary: Color(0xFF11324A),
    secondaryContainer: Color(0xFF2A4657),
    onSecondaryContainer: Color(0xFFD3E8F2),
    tertiary: Color(0xFFEDBE5C),
    onTertiary: Color(0xFF4A3A18),
    tertiaryContainer: Color(0xFF5A4118),
    onTertiaryContainer: Color(0xFFFAE7BD),
    error: _errorDark,
    onError: _onErrorDark,
    errorContainer: _errorContainerDark,
    onErrorContainer: _onErrorContainerDark,
    surface: Color(0xFF241209),
    onSurface: Color(0xFFFFE8DD),
  ),
  incomeLight: const Color(0xFF298E5C),
  expenseLight: const Color(0xFFBC2F3B), // was identical to primary — fixed
  successLight: const Color(0xFF2C9658),
  warningLight: const Color(0xFFD48535),
  infoLight: const Color(0xFF3795BE), // was identical to secondary — fixed
  primaryGradientStartLight: const Color(0xFFB23600),
  primaryGradientEndLight: const Color(0xFFFF6D2D),
  incomeDark: const Color(0xFF53C68C),
  expenseDark: const Color(0xFFD7757D),
  successDark: const Color(0xFF5EC98B),
  warningDark: const Color(0xFFDEAD7C),
  infoDark: const Color(0xFF79B8D2),
  primaryGradientStartDark: const Color(0xFFFF5212),
  primaryGradientEndDark: const Color(0xFFFFAB8C),
);
